[tool.poetry]
name = "python-reusables"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
google-cloud-pubsub = "^2.9.0"
pytest = "^7.0.0"
docker = "^5.0.3"
tinydb = "^4.6.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
